name: Airdop sui for test

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  airdrop-some-sui:
    runs-on: ubuntu-latest
    steps:
      - name: Airdrop SUI to  🔧
        run: |
          curl -d '{"FixedAmountRequest":{"recipient":"0x04aec9c55ac040784e333cf547a75455cceae4331c8199a785d7b39d6d6dbd4e"}}' -H 'Content-Type: application/json' https://faucet.testnet.sui.io/v1/gas
