name: Airdop sui for test

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  airdrop-some-sui:
    runs-on: ubuntu-latest
    steps:
      - name: Airdrop SUI to  🔧
        run: |
          curl -d '{"FixedAmountRequest":{"recipient":"0x0bd031da8a2bf03680d3e1919de107903879f14e8f447d4f1891c7ead8b678b2"}}' -H 'Content-Type: application/json' https://faucet.testnet.sui.io/v1/gas
